language: ruby

rvm:
  - 1.9.3
  - 2.0.0
#  - rbx

services:
  - redis-server

install:
  - bundle install --jobs=3 --retry=3 --deployment

before_script:
  - cp test/travis_ci_redis.json config/redis.json

script:
  - bundle exec rake
